apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-swiz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-swiz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-swiz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-swiz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-swiz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-zhlm-tenant/rhtap-demo-app/hacbs-test-project-swiz@sha256:a9e80a3a7b49d3065df62981a81eebdadb0c7321388ea4ddf95fd36481cc1899
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
